language: node_js
node_js:
- '6.1'
cache:
  directories:
  - node_modules
  - "$HOME/.npm"
  - "$HOME/.gem"
before_install:
- npm install -g gulp
script:
- gulp test
- gulp
deploy:
  provider: npm
  email: me@brianneisler.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: S3O1pxfDEhiVby+1pqTlWJeZQdXtyFdXexoYUHtHaHdy7TKQjneHDf/NLpoas3WYKZjnNHfmFik8k6hIgbWYk56rUlOKF3w18dzpDv8R8v6OfodEVp0EaX/H2eTem25nuhrqVEbxiZa+M62JBx/dkOSMzJ2VZoB+MiHo+V0gcOE9LXLCEX96Ep7nxaVN/YqkJsH7ZYkns3wAMQb8X7oMnOExG4PR9eoT5sikFpylS7p/MVIbTr5wNPysp9QOpjE1jayCijRzmdeSMakR+hCSKlxc16PivdBKKZC4xql7UxIXK4PZvkcZAMf6V9BVlz9V/axdM1z4dEMQqDR+ZgmTQ+RvuDEVVAP0OnEf4G2dgsE47MbhLfBDNfNL7w+X3rDutuobqIrHVXrItBw+6JWoKkOHcjMyxRq3QSoIMN6O6VbGQHV5EUIgGLqL8Laqq9RMftnkmWVMaQZ2TifnPy8R78p2gi59Cnfe+YmOGqyJLeopR9t8+eAKgLEt+cto+MjXLGvpWKaUBvSxar8TM5/2jRodRBzu+6gzViCB3gkMaw4kQxTM2WBAmOzDQ/qhJBulAKxvWpkBksg4dI+ybHTk60cztgFPHq/8PoR+va7cq5XHM1qyINRE347k5YXvUgB5F0n5rlJuqYRueBl4sUsCp/lzLjp7z03jCLwo9Hj2MGg=
